#import "Screen.js";
#import "env.js";
#import "CheckAllButtonsFromCamera.js";
#import "Check That Can Load Image As Text Color.js";
#import "Check all color Preset.js";
#import "Watermark.js";
#import "Sliders.js";
#import "UI_Monkey.js";
#import "Settings buttons checking.js";
#import "Checking all Dividers from artwork.js";
#import "Sandbox.js";
#import "sliderFromEraser.js";